language: node_js
node_js:
  - 7
deploy:
  provider: heroku
  api_key:
    secure: fkbeKvB3XWm+FdPKZYfgD2Ohz/yZwTqIMh9kHLA7WWXS4fd/nQkiWGQRfmFMVU1l1qGolZNh6ieqZT+NztuebjuzF15WtdHA0onXurBz61POeElGk8LrCbyL2T19Giqb97nKcTVpL3klkGzJDlJs3/TaNW8mnZgMt3Oat3wAAUu0hicBsArIcoIkvpD/Dd18tPoXZNgoL/kJ4ly6yjYaUaatf+dkpwRDyTCP8f2pKsWwYU3egJDoTnDCSDx9UEbadApRdfM+H/9hU+hYyuN/rvqRtTI6GlXzbz7aQyYT3i7ViTukS1fslHjjX0YjWy3YtyN5lu+N7inPOdf/A0G2gIW8jBP1EddmZiQexUyqDNU9ReSzOQE/W1jSZr6M1/VxUGevSNVat4dJPo5fRyz5Y5GeKmMqo+M8p9IdP/pIEHaOLsxOTpN8W+e+Ah/dBY0hkNsSS72GVxR4qhPZKvIP8+D6NckvE4P2egjii1oOpkJ5UrNiFR+EM6f6H5SMH2A+DMWKfpGNcrcatX79boFbE4YXX2JQouYpCgKHpL5tcVRQXWUtnCMdV8OYH29Dh98ZeolcIO9GHlZmYUr5F+hyVmEh5fCz7avAyEw8DZQf2GWzBplM1qzqf8iDgI6ZZ53sEugYEJL8hAXmm5H8N0lRCbRvnvHNPtVR/Qj4sqPxYdY=
  app: isapi-alertas
